service: serverless-aws-nodejs

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  timeout: 30
  stage: dev

# You can import other .yml routes
# In this case it is better to organize if you have many routes
# The name of your functions it will be '<service>-<stage>-<functionName>'
functions:
    - ${file(src/auth/auth-route.yml)}
    - ${file(src/hello-world/hello-world-route.yml)}
    - ${file(src/pokemon/pokemon-route.yml)}

plugins:
  - serverless-offline
