service: serverless-aws-nodejs

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  timeout: 30
  stage: dev

# The name of your function it will be '<service>-<stage>-<functionName>' in this case
# the function name is 'serverless-aws-nodejs-dev-hellow-world'
functions:
  hello-world:
    handler: src/hello-world/hello-world-handler.hello
    events:
        - http:
            path: /hello
            method: get
            cors: true

  pokemon:
    handler: src/pokemon/pokemon-handler.getById
    events:
        - http:
            path: /pokemon/{id}
            method: get
            cors: true
    environment:
      URL_POKEMON_API: http://pokeapi.co/api/v2

plugins:
  - serverless-offline