version: 2
jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:8.10
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - dependencies-cache-{{ checksum "package.json" }}
                 # fallback to using the latest cache if no exact match is found
                - dependencies-cache
            # Install project dependencies
            - run:
                name: Install Serverless CLI and dependencies
                command: |
                    sudo npm i -g serverless
                    npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: dependencies-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Deploying
                command: sls deploy -v

workflows:
    version: 2
    # The deploy workflow
    serverless_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master


